"""HelpとDOCX操作説明書で共有する、利用者向けの順序整理済み章データ。"""

MANUAL_SCREENSHOTS = {
    "1. 画面構成": ["test1_home_latest.png", "test1_presets.png"],
    "2. 起動と終了": "test2/poweroff.png",
    "3. 共通設定": [
        "test2/settings.png", "test2/frequency.png", "test2/symbolrate.png",
        "test2/fec.png", "test2/modulation.png", "test2/videosource.png",
        "test2/streamoutput.png", "test2/rxgain.png", "test2/txpower.png",
    ],
    "5. 送信": "test2/tx.png",
    "6. 受信": "test2/rx.png",
    "7. 通常運用の手順": "test2/rssi.png",
    "10. Help・診断・アプリ再起動": ["test2/manual.png", "test2/diagnostic.png"],
    "11. Langstone": "test1_langstone.png",
}

MANUAL_SECTIONS = [
    ("重要", [
        ("Plutoのユーザー名・パスワード",
         "Plutoのユーザー名(root)とパスワード(analog)は、デフォルト値のまま変更しないでください。本アプリとLangstoneは、SSHでPlutoにログインしてリブートや設定ファイルの書き込みを行っています(アプリ起動時・アプリ再起動・機器試験・送受信開始時・Langstone終了時)。変更するとPlutoをリブートできなくなります。"),
    ]),
    ("1. 画面構成", [
        ("このアプリでできること",
         "Shonan_Liteは、無印ADALM-Plutoを使ってDVB-S2 DATVの送信・受信・RFループバック試験を行うアプリです。ホーム画面から各機能へ移動します。"),
        ("ホーム画面",
         "「送信」「受信」「周波数」「RSSI測定」「シンボルレート」「誤り訂正(FEC)」「変調方式」「映像ソース」「出力設定」「RXゲイン」「TX出力」「設定」「機器試験」「ヘルプ」「アプリ再起動」「電源オフ」「Langstone」「プリセット」「Pluto電源」を表示します。各カードはアイコン・日本語名・英語名を同じ配置で表示します(英語表示では英語名のみ)。周波数カードには現在の周波数を表示します。背景右側の衛星をタップすると、Langstoneを10GHz受信用のバンドで開きます(9章参照)。"),
        ("画面の共通操作",
         "カードまたはボタンをタップして画面を開きます。各画面の「ホームへ戻る」でホーム画面へ戻ります。送受信中に設定を変更する場合は、先に送信・受信を停止してください。"),
    ]),
    ("2. 起動と終了", [
        ("起動前の接続",
         "Plutoを起動し、Pi 4とEthernet接続します。PlutoのIPアドレスは環境に合わせて設定します。TXとRXを試験する場合は、TXとRXを直結せず、必ず外部アッテネータを用意します。"),
        ("電源投入後の動作",
         "電源投入後は起動メニューでShonan_LiteまたはLangstoneを選択します。Shonan_Lite起動時は、ホーム画面表示前にPlutoの再起動、オフライン確認、再接続確認、設定再適用を行います。Pluto確認に20秒以上かかる場合は確認をスキップしてホーム画面を表示します。"),
        ("アプリの終了",
         "送信中・受信中の場合は、先にそれぞれの停止ボタンを押します。停止を確認してからホーム画面の「電源オフ」を使用します。"),
        ("安全上の注意",
         "送信出力を受信入力へ直結しないでください。RFループバックでは TX → 40 dB以上の外部アッテネータ → RX の順に接続します。"),
    ]),
    ("3. 共通設定", [
        ("設定を始める前に",
         "相手局と先に次の共通値を決めます。周波数437.000 MHz、シンボルレート500 kS/s、変調QPSK、FEC 3/5、パイロットONを標準例とします。送信側と受信側でこの5項目が一致しないと受信できません。"),
        ("1. 設定画面：基本設定",
         "ホーム画面で「設定」をタップします。表示言語(日本語/English)を選び、送信先(Pluto Tx)にPlutoのIPアドレスを入力します(UDP-TSポートは8282固定)。PA_Power/PTTコントローラ(ESP32)を使う場合は「ESP32 W5500を使用する」をONにしてIPアドレスを入力します(OFFまたは空欄なら連携しません。OFFにしてもIPアドレスは保持されます)。使用する場合、送信開始/終了に連動してPTTを、アプリ起動/終了に連動して12V電源を自動でON/OFFします。入力後にキーボードを閉じ、入力欄からフォーカスが外れたことを確認します。PlutoのIPアドレスを相手局と混同しないようにしてください。"),
        ("ESP32 W5500なしでのPA/LNA制御",
         "ESP32 W5500(PA_Power/PTTコントローラ)を使わなくても、RasPI4からのPTT ON信号でPA・LNAの送受信切替を制御できます。送信中はPi 4のGPIO21(40番ピン、GNDは39番ピン)がHIGH(3.3V)、受信中はLOWになります。Shonan_Liteの送信とLangstoneの送信(Langstone標準のTx Output)のどちらでも同じピンに出力されます。GPIO21は電流を取れないため、トランジスタやリレードライバ等でバッファしてからPA・LNA(同軸リレー等)を駆動してください。12V電源のON/OFFとホーム画面の「Pluto電源」カードはESP32 W5500が必要です。"),
        ("2. 周波数画面",
         "ホーム画面で「周波数」をタップします。相手局と決めた周波数を入力し、「OK」または確定ボタンをタップします。ホーム画面の周波数カードが同じ値に変わったことを確認します。標準例は437.000 MHzです。"),
        ("10GHz帯とLNB",
         "周波数画面のバンド選択で「10GHz帯」を押すと、LNBを使用するかどうかを確認します。「はい」を選ぶと表示周波数は10.2365 GHz(10,236,500 kHz)になり、受信時はLNB局部発振9750 MHzを引いた486.5 MHzでPlutoが受信します(受信画面・RSSI測定も同じ)。LNB使用中は受信専用で、送信はできません。「いいえ」を選ぶと従来どおり10,180 MHz(LNBなし)です。「10GHz帯」を押し直すと選び直せ、他のバンドを選ぶとLNBは解除されます。LNBへの電源供給(同軸経由のバイアスT)は別途用意してください。"),
        ("3. シンボルレート画面",
         "ホーム画面で「シンボルレート」をタップし、500 kS/sを選択します。確定後、カード表示が500 kS/sになったことを確認します。相手局と異なる値にしないでください。"),
        ("4. 変調方式画面",
         "ホーム画面で「変調方式」をタップし、相手局と同じ方式を選択します。初めて接続する場合はQPSKを使用します。選択肢はQPSK・8PSKです。選択後にホームへ戻り、変調方式カードを確認します。"),
        ("5. 誤り訂正(FEC)画面",
         "ホーム画面で「誤り訂正」をタップし、相手局と同じFECを選択します。標準例は3/5です。選択肢は選択中の変調方式で実際に動作する組み合わせのみに絞り込まれます(QPSK: 1/2・3/5・8/9、8PSK: 3/5・8/9)。FECだけを変更しても変調方式が合わなければ受信できません。"),
        ("6. 映像ソース画面",
         "ホーム画面で「映像ソース」をタップします。実映像を送る場合は「カメラ」(USBカメラを接続してから選択)、映像系を先に確認する場合は「テストパターン」を選びます。「ファイル選択」では静止画(png/jpg/jpeg/bmp)を選び、反復して送信します。右側のプレビューで選んだ映像を確認できます。カメラは1280x720で取り込みます(対応していればMJPEG・30fps。1280x720に対応しないカメラは既定の解像度)。暗い場所ではカメラが露出を優先してフレームレートを下げることがあります。カメラ選択時は「撮影」ボタンでカメラ映像をJPG(1920x1080)として撮影でき、ホームフォルダのPictures/Shonan_Liteに保存されます。保存した画像は「ファイル選択」(このフォルダから開きます)で送信画像として選べます。送信中は撮影できません。画面下部の「コールサイン」「備考」(任意)に入力した文字は映像に焼き込まれ、日時も右下に表示されます。各入力欄の右で文字サイズ(コールサイン36〜256px、備考16〜64px)と文字色(白・黄・赤・緑・青・水色・橙・黒)を選べます。カメラ映像と画像ファイルに適用され、テストパターンには適用されません。送信映像はフルHD(1920x1080)固定で、縦横比が異なる映像は黒帯を付けて収めます。音声はカメラ内蔵マイクの音をモノラルで映像と一緒に送ります(マイクが無いときは無音)。"),
        ("7. 出力設定画面",
         "ホーム画面で「出力設定」をタップします。「Pluto URI」にPlutoのIPアドレスを入力するか、「自動検出」を押して同一LAN上のPlutoを探します(見つかると入力欄へ自動で反映します。見つからない場合は電源とLAN配線を確認してください)。「送信先ポート(Pluto側固定)」は8282固定で変更できません。「受信TSポート」「ステータスポート」は必要に応じて変更します。"),
        ("8. RXゲイン画面",
         "ホーム画面で「RXゲイン」をタップします。自動調整する場合はAGCをON、相手局と固定条件で試験する場合はAGCをOFFにして手動ゲインを設定します。標準試験値は60 dBです。"),
        ("9. TX出力画面",
         "ホーム画面で「TX出力」をタップし、接続するアンテナまたはアッテネータに合わせて出力減衰量を設定します。0 dBが最大出力で、値を小さく(-側に)するほど出力が下がります。設定値は送信画面の「出力減衰」にdBで表示されます。RFループバックでは必ず40 dB以上の外部アッテネータを使用します。"),
        ("10. オンデバイス復調と通常運用",
         "ホーム画面の「設定」でオンデバイス復調をONにするとTX/RX同時動作も自動的にONになります。ONにする操作をすると、PlutoのTX端子とRX端子の間に40 dB以上の外部アッテネータが入っているかを確認するポップアップが表示され、「はい」を選んだ場合のみONになります。受信開始時にTXは自動開始しません。通常の別々の送信・受信ではOFFにします。OFFではTXとRXは排他的に動作します。"),
        ("設定完了の確認",
         "ホーム画面に戻り、周波数、シンボルレート、FEC、変調方式、映像ソース、RXゲイン、TX出力のカードを順番に読み上げて確認します。相手局にも同じ値を読み上げてもらい、1項目ずつ一致を確認してから送信・受信を開始します。"),
    ]),
    ("4. プリセット", [
        ("プリセットの適用",
         "ホーム画面の「プリセット」を開き、プリセット1～5から選択します。プリセット1は初期状態でRFループバック（437.000 MHz / 500 kS/s / QPSK / FEC 3/5）です。選択すると設定値を一括適用し、Plutoにも反映します。送信・受信は自動開始しません。"),
        ("新規登録",
         "各設定画面で周波数、シンボルレート、変調、FEC、映像ソースなどを手動設定します。プリセット画面へ戻り、登録したい行の「登録/変更」を押します。キーボードからプリセット名を入力して保存します。"),
        ("既存プリセットの変更",
         "設定値を手動で変更した後、変更したいプリセット行の「登録/変更」を押すと、現在の設定値で上書きできます。削除は「削除」ボタンを押します。登録・変更・削除は送受信停止中に行ってください。"),
    ]),
    ("5. 送信", [
        ("送信開始",
         "ホーム画面の「送信」は送信画面を開くだけです。送信画面で映像プレビューと設定値を確認し、「送信開始」を押します。受信も動作中の場合は、アプリがRX停止 → TX設定反映 → TX開始 → RX再開の順で切り替えます。"),
        ("送信中の確認",
         "送信画面で映像プレビューと、周波数・シンボルレート・変調方式・FEC・出力減衰(dB)を確認します。「パケット数」はPlutoへ送ったUDPパケットの累計、「フレーム数」は符号化した映像フレーム数で、送信中は増え続けます(送信停止で0に戻ります)。「接続」が「接続中」ならPlutoへ送出できています。送信開始を押しても受信は自動開始しません。"),
        ("送信停止",
         "送信終了時は「送信停止」を押します。停止表示を確認してから設定や配線を変更します。"),
    ]),
    ("6. 受信", [
        ("受信開始",
         "送信側と周波数、シンボルレート、変調方式、FEC、パイロットを一致させます。ホーム画面の「受信」を開き、「受信開始」を押します。"),
        ("受信中の確認",
         "LOCK、SOF、パケット数、ビットレート、エラー数を確認します。パケット数とSOFが増え、エラーが増えないことを確認してから映像表示を確認します。"),
        ("映像が表示されない場合",
         "まずLOCKとパケット数を確認します。RF受信が正常なら、映像ソース、H.264映像、送信開始状態、テストパターン設定を確認します。画面が黒い場合は、周波数、シンボルレート、FEC、変調方式、配線も再確認します。"),
        ("受信停止",
         "受信終了時は「受信停止」を押します。送信も行っている場合は、受信停止後に送信停止を押します。"),
    ]),
    ("7. 通常運用の手順", [
        ("相手局と接続する手順",
         "1) 相手局と共通値を決めます。2) 3章の各設定画面をPi 4側で順番に設定します。3) ホーム画面のカードを相手局と照合します。4) 相手局が送信する場合は、先に受信開始を押して待機します。5) 自局が送信する場合は、送信開始を押してから相手局へ送信開始を連絡します。6) 受信画面でLOCK、SOF、パケット数、エラー数、映像を確認します。"),
        ("RSSI測定(相手局の周波数を探す)",
         "ホーム画面の「RSSI測定」で、中心周波数(周波数画面の値)の前後を±5/±10/±20MHzの範囲でスキャンし、受信レベル(RSSI)をグラフ表示します。ステップ(kHz)はテンキーで入力します。「検索開始」でスキャンし、「最も強い周波数」を表示します(RSSIは値が小さいほど強い信号です)。「検索方法」は「連続」(検索停止まで繰り返す)と「1回」から選び、RXゲイン(AGC/手動)も画面右側で調整できます。設定画面の「オンデバイス復調」がOFF(通常運用)のときは送信せず、相手局の電波を測ります(相手局が送信していなければグラフは平らです)。ONのときはテスト用の機能で、自局も映像ソースに関係なくテストパターンで自動送信し、自分の信号を測ります(必ず40 dB以上のアッテネータを介してください)。"),
        ("送信運用",
         "1) 3章の設定を完了します。2) ホーム画面で送信を開きます。3) 映像プレビューを確認します。4) 送信開始を押します。5) 送信中表示と映像を確認します。6) 終了時は送信停止を押します。"),
        ("受信運用",
         "1) 送信側と全パラメータを一致させます。2) ホーム画面で受信を開きます。3) 受信開始を押します。4) LOCK、SOF、パケット数、エラー数、映像を確認します。5) 終了時は受信停止を押します。"),
        ("送受信運用",
         "1) 送信を開始します。2) 受信を開始します。3) 受信画面でLOCK、SOF、パケット数、エラー数、映像を確認します。4) 終了時は受信停止、送信停止の順に停止します。"),
    ]),
    ("8. 送受信・RFループバック試験", [
        ("試験前の設定値",
         "周波数: 437.000 MHz、シンボルレート: 500 kS/s、変調方式: QPSK、FEC: 3/5、ロールオフ: 0.35、フレーム: Long Frame、RXゲイン: 60 dB、映像ソース: テストパターン、パイロット: ON、オンデバイス復調: ON、TX/RX同時動作: ON、RFループバック: ON。"),
        ("設定の意味",
         "オンデバイス復調は同一PlutoでTX/RX同時動作を許可する設定です。RFループバックは、送信RFをアッテネータ経由で受信RFへ戻す試験経路の設定です。オンデバイス復調ONだけではRF配線試験になりません。"),
        ("試験手順",
         "1) TX → 40 dB以上のアッテネータ → RXを接続、2) プリセット1または試験パラメータを適用、3) 送信画面で「送信開始」、4) 3～5秒待つ、5) 受信画面で「受信開始」、6) LOCK、SOF、パケット数、エラー数、映像表示を確認します。"),
        ("合格の目安",
         "LOCKが成立し、SOFとパケット数が継続して増加し、エラーが増えず、テストパターンが表示されればRFループバック試験は成功です。"),
    ]),
    ("9. Langstone", [
        ("起動と切替",
         "起動メニューまたはホーム画面のLangstoneカードを選択します。LangstoneとShonan_Liteは同じPlutoを使用するため、同時には起動しません。"),
        ("基本操作",
         "Langstone画面下部のBAND、MODE、SET、BEACON、PTTなどをタップして操作します。"),
        ("Shonan_Liteへ戻る",
         "LangstoneのSET画面で「GOTO SHONAN_LITE」を押します。Langstoneを停止してShonan_Liteへ切り替えます。切替時間を短くするため、切替のときはPlutoを再起動しません(Langstoneが止めた送信LOは元に戻します)。電源投入時・アプリ再起動などでは従来どおりPlutoを再起動します。"),
        ("10GHz受信(衛星をタップ)",
         "ホーム画面の背景右側の衛星をタップすると、Langstoneを10GHz受信用のバンド(表示10236.5 MHz、Pluto受信486.5 MHz、LNB局部発振9750 MHz)で開きます。このバンドは受信専用で、PTTボタンは灰色の「RX ONLY」表示になり、PTT・CWキー・ビーコンのいずれでも送信しません。普通のLangstoneカードで開くと、衛星の前に使っていたバンドに戻ります。"),
    ]),
    ("10. Help・診断・アプリ再起動", [
        ("Help",
         "Helpでは章を選択して操作手順を確認できます。プリセットの登録・適用方法、送受信手順、RFループバック試験手順は本書と同じ順番で表示されます。"),
        ("機器試験",
         "機器試験の「全体試験」は、送信・受信を停止してから押します。最初にPlutoを再起動して接続を確認し、次の4項目を順に試験して結果を表に表示します: Pluto SDR接続(IIOコンテキスト接続)、送信テスト(8秒間の送出継続)、受信テスト(8秒間の受信継続)、温度センサー(Pi 4のCPU温度)。最後に「TX: 正常 / RX: 正常」のように総合結果を表示します。試験の実行中は、押したボタンが赤で表示されます。終了時は送信・受信とも自動で停止します。「カメラ＋音声診断」はUSBカメラの映像と内蔵マイクの音声を実際に取り込んで送出できるかを確認します。診断結果はアンテナ性能やRF環境を保証するものではありません。"),
        ("アプリ再起動",
         "送受信を停止してから「アプリ再起動」を使用します。Plutoを再起動し、オフライン確認、Web UI・IIOの復旧確認、保存済み設定の再適用を順番に行います。確認できない場合はホーム画面を表示します。"),
    ]),
    ("11. トラブルシューティング", [
        ("送信できない",
         "送信画面へ移動しただけでは送信されません。「送信開始」を押し、Pluto IP、周波数、映像ソース、TX出力を確認します。"),
        ("受信できない",
         "送信側と受信側の周波数、シンボルレート、変調方式、FEC、パイロットを一致させ、TXが送信中であること、アッテネータと配線、RXゲインを確認します。"),
        ("SOF・パケット数が増えない",
         "Plutoの設定値、周波数、シンボルレート、変調方式、FEC、パイロット、RXゲイン、TX出力、アッテネータを確認します。"),
        ("Plutoに接続できない",
         "Plutoの電源、IPアドレス、Ethernet接続を確認します。アプリ再起動またはPluto再起動後は、設定再適用が完了してから送受信を開始します。"),
        ("映像が黒い",
         "LOCKとパケット数が正常なら、テストパターンへ切り替えて映像系を切り分けます。送信側のH.264エンコードと受信側の映像デコードが動作していることを確認します。"),
    ]),
    ("12. Plutoと接続情報", [
        ("Pluto設定の確認", "Pluto無印でF5OEO製DATVカスタムファームウェアを使用します。周波数、変調、シンボルレート、FEC、パイロット、フレーム、ロールオフがアプリ設定と一致していることを確認します。"),
        ("Pi4", "ホスト名: DVB-S2-PI4。IPアドレスとSSH接続先は使用環境に合わせて設定します。"),
        ("試験の標準値", "周波数437.000 MHz、500 kS/s、QPSK、FEC 3/5、テストパターン、RXゲイン60 dBを標準試験値とします。"),
    ]),
    ("13. 注意事項と検証範囲", [
        ("検証について", "本書の内容は実機で動作確認した内容に基づきます。ただし、使用するPluto、RF配線、電源、ネットワーク、映像機器の組み合わせによっては、まだバグが内在している可能性があります。"),
        ("RF安全", "送信機と受信機の接続条件を確認し、指定値以上のアッテネータを使用してください。"),
        ("クレジット", "受信部の方式考案・原システム設計: 山崎慎慈氏(JE1BTA)。受信部安定化調査・本アプリ開発: 真城和一。"),
    ]),
]

# 英語表示のHelp(screens/manual.py)と、DOCX操作説明書の英語編で使う。
# 日本語章とは項目数が異なる(日本語の方が詳しい)。
MANUAL_SECTIONS_EN = [
    ("Important", [
        ("Pluto username and password", "Keep the Pluto's username (root) and password (analog) at their default values. This app and Langstone log in to the Pluto via SSH to reboot it and write its settings file (at app start, app restart, equipment test, TX/RX start and Langstone exit). If they are changed, the Pluto cannot be rebooted."),
    ]),
    ("1. Overview", [
        ("What this app does", "Shonan_Lite is a DVB-S2 DATV transmitter, receiver, and RF loopback test tool for ADALM-Pluto."),
        ("Home screen", "Use the cards for Transmit, Receive, Frequency, RSSI Measurement, Symbol Rate, FEC, Modulation, Video Source, Stream Output, RX Gain, TX Power, Settings, Diagnostic, Help, App Restart, Power Off, Langstone, Presets, and Pluto Power. Every card shows its icon and name in the same layout; the Frequency card also shows the current frequency. Tapping the satellite on the right of the background opens Langstone on the band for 10 GHz reception (see chapter 9)."),
        ("Common operation", "Tap a card or button to open it. Use Back to Home to return. Stop transmit and receive before changing operating parameters."),
    ]),
    ("2. Startup and shutdown", [
        ("Before startup", "Power on Pluto and connect it to Pi 4 over Ethernet. Set the Pluto address for your network."),
        ("Startup sequence", "The startup menu selects Shonan_Lite or Langstone. Shonan_Lite restarts Pluto, checks the connection, and reapplies settings before showing Home. If confirmation takes over 20 seconds, it continues to Home."),
        ("Shutdown", "Stop transmit and receive, then use Power Off from Home."),
        ("RF safety", "Never connect TX directly to RX. Use TX → external attenuator of at least 40 dB → RX."),
    ]),
    ("3. Operating parameters", [
        ("Standard example", "Frequency 437.000 MHz, symbol rate 500 kS/s, QPSK, FEC 3/5, and Pilot ON. TX and RX must use the same values."),
        ("Settings", "Open Settings, choose the display language (Japanese/English), and enter the Pluto IP address under Destination (Pluto Tx); the UDP-TS port is fixed at 8282. To use the PA_Power/PTT controller (ESP32), turn on \"Use ESP32 W5500\" and enter its IP address (the link is disabled when it is OFF or the address is empty; the IP address is kept even when OFF). When used, PTT follows TX start/stop and the 12 V power is switched ON/OFF automatically at app start/exit."),
        ("PA/LNA control without ESP32 W5500", "Even without the ESP32 W5500 (PA_Power/PTT controller), the PA and LNA can be switched between TX and RX by the PTT ON signal from the RasPI4. GPIO21 on the Pi 4 (pin 40; GND on pin 39) is HIGH (3.3 V) while transmitting and LOW while receiving, both for Shonan_Lite and for Langstone (Langstone's standard Tx Output). GPIO21 cannot supply current, so buffer it with a transistor, relay driver or similar before driving the PA and LNA. Switching the 12 V power ON/OFF and the Pluto Power card still require the ESP32 W5500."),
        ("Frequency", "Enter the agreed frequency and press OK. Confirm that the Home card shows the same value."),
        ("10 GHz band and LNB", "Pressing 10GHz Band in the band selection on the Frequency screen asks whether to use an LNB. Choosing Yes sets the displayed frequency to 10.2365 GHz (10,236,500 kHz), and when receiving the Pluto receives at 486.5 MHz, i.e. minus the 9750 MHz LNB local oscillator (the same applies to the RX screen and RSSI measurement). While the LNB is in use it is receive only and transmitting is not possible. Choosing No gives 10,180 MHz (no LNB) as before. Press 10GHz Band again to choose again; selecting another band cancels the LNB. Provide power for the LNB (bias-T over the coax) separately."),
        ("Symbol Rate", "Choose or enter the agreed symbol rate. The standard example is 500 kS/s."),
        ("Modulation and FEC", "Select the same modulation and FEC as the other station. Modulation is QPSK or 8PSK, and the FEC choices are limited to working combinations (QPSK: 1/2, 3/5, 8/9; 8PSK: 3/5, 8/9). QPSK and FEC 3/5 are the standard example."),
        ("Video Source", "Choose Camera for live video, Test Pattern for diagnostics, or File to send a still image (png/jpg/jpeg/bmp); the preview on the right shows the selected source. The camera is captured at 1280x720 (MJPEG at 30 fps when supported; cameras without 1280x720 use their default size), and in dim light the camera may lower its frame rate. With Camera, Capture saves a 1920x1080 JPG to Pictures/Shonan_Lite (not while transmitting), and File opens that folder. The Callsign and Note fields are burned into camera and image video with the date and time; choose their font size and color next to each field. The transmitted video is fixed at Full HD (1920x1080) with black bars when the aspect ratio differs. Audio from the camera's built-in microphone is sent with the video in mono (silence when no microphone is found)."),
        ("Stream Output", "Enter the Pluto IP address in Pluto URI, or press Detect to find the Pluto on the same LAN automatically. The destination port is fixed at 8282 on the Pluto. Change the RX TS port and Status port only if needed."),
        ("RX Gain and TX Power", "Use AGC or set RX gain manually. The standard test gain is 60 dB. TX Power sets the output attenuation: 0 dB is maximum output, and the value is shown as TX Attenuation (dB) on the Transmit screen."),
        ("On-device demodulation", "ON automatically enables TX/RX simultaneous operation, but starting RX does not automatically start TX. Turning it ON first asks you to confirm that an attenuator of 40 dB or more is connected between the Pluto TX and RX ports. OFF keeps TX and RX exclusive."),
        ("Final check", "Read every Home card and compare frequency, symbol rate, modulation, FEC, source, RX gain, and TX power with the other station."),
    ]),
    ("4. Presets", [
        ("Apply", "Open Presets and select one of five entries. The values are applied to the app and Pluto; transmit and receive do not start automatically."),
        ("Register or edit", "Set values manually in the individual screens, return to Presets, press Save / Edit, and enter the preset name with the keyboard."),
        ("Delete", "Press Delete on the selected row. Edit and delete while transmit and receive are stopped."),
    ]),
    ("5. Transmit", [
        ("Start", "Open Transmit, check the preview and parameters, and press Start Transmit. Opening the screen does not start transmission."),
        ("While transmitting", "Check the preview, frequency, symbol rate, modulation, FEC, and TX attenuation (dB). Packets is the total number of UDP packets sent to the Pluto and Frames is the number of encoded video frames; both keep increasing while transmitting and return to 0 when stopped. Connection shows Connected while the stream is being sent to the Pluto."),
        ("Stop", "Press Stop Transmit before changing settings or wiring."),
    ]),
    ("6. Receive", [
        ("Start", "Match frequency, symbol rate, modulation, FEC, and Pilot with the transmitting station, then press Start Receive."),
        ("Check", "LOCK, SOF, packets, bitrate, errors, and the video image should be monitored. SOF and packets must continue to increase."),
        ("No video", "First check LOCK and packets, then check video source, H.264 encoding, transmitter state, test pattern, and wiring."),
        ("Stop", "Press Stop Receive when finished."),
    ]),
    ("7. Normal operation", [
        ("Station-to-station procedure", "Agree on all parameters, configure each screen in order, compare Home cards, start RX or TX as required, and verify LOCK, SOF, packets, errors, and video."),
        ("RSSI Measurement", "RSSI Measurement scans ±5/±10/±20 MHz around the center frequency (from the Frequency screen) and graphs the received level; a smaller RSSI value means a stronger signal. Choose Repeat or Once, and adjust RX gain (AGC/manual) on the right. With on-device demodulation OFF (normal operation) it does not transmit and measures the other station. With it ON (a test feature) your station also transmits the test pattern automatically and measures its own signal; always use an attenuator of 40 dB or more."),
        ("TX/RX switching", "When TX starts while RX is active, the app performs RX stop → TX configuration → TX start → RX restart."),
    ]),
    ("8. TX/RX and RF loopback test", [
        ("Test values", "437.000 MHz, 500 kS/s, QPSK, FEC 3/5, Long Frame, roll-off 0.35, RX gain 60 dB, Test Pattern, Pilot ON, on-device demodulation ON, and RF loopback ON."),
        ("Important distinction", "On-device demodulation permits simultaneous TX/RX in one Pluto. RF loopback describes the physical attenuated RF path; it is not enabled by on-device demodulation alone."),
        ("Pass criteria", "LOCK is established, SOF and packet counts increase continuously, errors remain stable, and the test pattern is displayed."),
    ]),
    ("9. Langstone", [
        ("Switching", "Select Langstone from the startup menu or Home. Only one application uses Pluto at a time."),
        ("Return", "Use GOTO SHONAN_LITE in Langstone to stop it and return to Shonan_Lite. To shorten the switching time, the Pluto is not rebooted when switching (the TX LO that Langstone powered down is restored). The Pluto is still rebooted at power-up and app restart."),
        ("10 GHz reception (tap the satellite)", "Tapping the satellite on the right of the Home screen background opens Langstone on the band for 10 GHz reception (displayed 10236.5 MHz, Pluto RX 486.5 MHz, LNB local oscillator 9750 MHz). This band is receive only: the PTT button is shown grayed out as RX ONLY, and it does not transmit from PTT, the CW key or the beacon. Opening Langstone from the normal Langstone card returns to the band used before the satellite."),
    ]),
    ("10. Help, diagnostics, and restart", [
        ("Help", "Use the table of contents or search field to find an operating procedure."),
        ("Diagnostic", "Stop TX and RX, then press Full Test. It restarts the Pluto and checks four items in order: Pluto SDR connection (IIO context), TX test (8 s of continuous output), RX test (8 s of continuous reception), and temperature sensor (Pi 4 CPU temperature), then shows an overall TX/RX result. While a test is running, the pressed button is shown in red. TX and RX are stopped automatically at the end. Camera + Audio Diagnostic checks that the USB camera video and its microphone audio can actually be captured and sent. The result does not guarantee antenna or RF performance."),
        ("App Restart", "Stop TX/RX first. App Restart restarts Pluto, checks recovery, and reapplies saved settings in order."),
    ]),
    ("11. Troubleshooting", [
        ("Cannot transmit", "Check Pluto IP, frequency, video source, TX power, and that Start Transmit was pressed."),
        ("Cannot receive", "Match all five RF parameters and Pilot, confirm TX is active, and check attenuator, wiring, and RX gain."),
        ("SOF does not increase", "Recheck Pluto settings, frequency, symbol rate, modulation, FEC, Pilot, RX gain, TX power, and attenuation."),
        ("Cannot connect to Pluto", "Check power, IP address, and Ethernet. Wait for configuration reapplication after a restart."),
    ]),
    ("12. Pluto and connection information", [
        ("Firmware", "Use the F5OEO DATV custom firmware on an ADALM-Pluto. Pluto settings must match the app."),
        ("Pi 4", "Host name: DVB-S2-PI4. Configure the IP address and SSH destination for the operating environment."),
        ("Standard test", "437.000 MHz, 500 kS/s, QPSK, FEC 3/5, Test Pattern, and RX gain 60 dB."),
    ]),
    ("13. Notes and validation scope", [
        ("Validation", "This guide is based on actual equipment checks. Bugs may still exist depending on Pluto, RF wiring, power, network, and video equipment combinations."),
        ("Credit", "Receiver method and original system design: Shinji Yamazaki (JE1BTA). Receiver stabilization and application development: Kazuichi Shinjo."),
    ]),
]
